-- CreateEnum
CREATE TYPE "GeneralCondition" AS ENUM ('RAS', 'HYPERTENSION_ARTERIELLE', 'DIABETE', 'INSUFFISANCE_CARDIAQUE', 'INFARCTUS_DU_MYOCARDE', 'ENDOCARDITE', 'ASTHME', 'TUBERCULOSE', 'ALLERGIE', 'INSUFFISANCE_RENALE_CHRONIQUE', 'ANEMIES', 'RETARD_PSYCHOMOTEUR', 'EPILEPSIE', 'AUTRE');

-- AlterTable
ALTER TABLE "Patient" ADD COLUMN     "generalCondition" "GeneralCondition";
