export function formatToothName(number: number): string {
  const names: Record<number, string> = {
    11: "Incisive centrale sup. droite",
    12: "Incisive latérale sup. droite",
    13: "Canine sup. droite",
    14: "Prémolaire 1 sup. droite",
    15: "Prémolaire 2 sup. droite",
    16: "Molaire 1 sup. droite",
    17: "Molaire 2 sup. droite",
    18: "Molaire 3 sup. droite",
    21: "Incisive centrale sup. gauche",
    22: "Incisive latérale sup. gauche",
    23: "Canine sup. gauche",
    24: "Prémolaire 1 sup. gauche",
    25: "Prémolaire 2 sup. gauche",
    26: "Molaire 1 sup. gauche",
    27: "Molaire 2 sup. gauche",
    28: "Molaire 3 sup. gauche",
    31: "Incisive centrale inf. gauche",
    32: "Incisive latérale inf. gauche",
    33: "Canine inf. gauche",
    34: "Prémolaire 1 inf. gauche",
    35: "Prémolaire 2 inf. gauche",
    36: "Molaire 1 inf. gauche",
    37: "Molaire 2 inf. gauche",
    38: "Molaire 3 inf. gauche",
    41: "Incisive centrale inf. droite",
    42: "Incisive latérale inf. droite",
    43: "Canine inf. droite",
    44: "Prémolaire 1 inf. droite",
    45: "Prémolaire 2 inf. droite",
    46: "Molaire 1 inf. droite",
    47: "Molaire 2 inf. droite",
    48: "Molaire 3 inf. droite",
  };
  return names[number] ?? `Dent ${number}`;
}
